### ISSUE TITLE
Invalid redirect_uri Error on Login

### ISSUE THREAD

**Issue by shammils** [autodesk-platform-services/aps-hubs-browser-nodejs#2]
Running into an `Invalid redirect_uri` 400 error when clicking on the login button.

<img width="475" alt="Screenshot 2023-10-03 at 1 54 06 PM" src="https://github.com/autodesk-platform-services/aps-hubs-browser-nodejs/assets/16459104/ec184204-bb1c-4f43-a93a-3af8e3a1e1d8">

I cloned this repo as of yesterday, added an '.env' file and run the project using VSCode. Exposable .env file settings I have set:

- APS_CALLBACK_URL="http://localhost:8080/api/auth/callback"
- SERVER_SESSION_SECRET="custom-encryption-phrase-test"

My exposable application settings:

- Application Type: Traditional Web App
- Selected APIS: ALL
- Callback URL: http://localhost:8080/

Side note, my application configuration works successfully on the viewer project you created.

I noticed that you mentioned that the redirect URL must match the pattern of the callback URL field and I feel like that's possibly the issue here, but I can't seem to change that error modifying the application's Callback URL and APS_CALLBACK_URL.

**Comment by yiskang** [comment]
The callback url in the app in developer portal should be http://localhost:8080/api/auth/callback, not http://localhost:8080

**Comment by shammils** [comment]
yeah that was it, thank you for that. I was just coming here to delete this issue but you responded before that.

**Comment by shammils** [comment]
Feel free to ignore this question since this isn't the correct place to ask anyway.
I noticed the V2 auth files in the repo but V2 auth support does not seem to have been completed in any fashion in this repo. What is the status of V2 authentication in general?
